version: '3.8'
services:
  stats-service:
    build: stats-service/stats-server
    image: stats-server
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - URL=jdbc:postgresql://stats-db:5432/stats_db
      - USERNAME=root
      - PASSWORD=root
      - TZ=Europe/Yekaterinburg

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - TZ=TZ=Europe/Yekaterinburg

  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - URL=jdbc:postgresql://ewm-db:5433/ewm_db
      - USERNAME=root
      - PASSWORD=root
      - TZ=Europe/Yekaterinburg

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - TZ=TZ=Europe/Yekaterinburg