CREATE TABLE IF NOT EXISTS users (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
email VARCHAR(254),
name VARCHAR(250),
    CONSTRAINT pk_users_id PRIMARY KEY(id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS category (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name VARCHAR(50),
    CONSTRAINT pk_category_id PRIMARY KEY(id),
    CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS event (
id BIGINT GENERATED BY DEFAULT AS IDENTITY,
annotation VARCHAR(7000),
category_id int,
confirmed_requests int,
created_on TIMESTAMP WITHOUT TIME ZONE,
description VARCHAR(7000),
event_date TIMESTAMP WITHOUT TIME ZONE,
user_id INTEGER,
lat double precision,
lon double precision,
paid boolean,
participant_limit INTEGER,
published_on TIMESTAMP WITHOUT TIME ZONE,
request_moderation boolean,
state int,
title VARCHAR(120),
    CONSTRAINT pk_event_id PRIMARY KEY(id),
    CONSTRAINT users_event_user_id_fk
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT category_event_category_id_fk
            FOREIGN KEY (category_id) REFERENCES category (id)
);

CREATE TABLE IF NOT EXISTS request (
id BIGINT GENERATED BY DEFAULT AS IDENTITY,
created TIMESTAMP WITHOUT TIME ZONE,
event_id int,
requester_id int,
status VARCHAR(20),
    CONSTRAINT pk_request_id PRIMARY KEY(id),
    CONSTRAINT event_request_event_id_fk
        FOREIGN KEY (event_id) REFERENCES event (id),
    CONSTRAINT user_requester_requester_id_fk
        FOREIGN KEY (requester_id) REFERENCES users (id),
    CONSTRAINT event_unique_uq UNIQUE (event_id, requester_id)
);

CREATE TABLE IF NOT EXISTS compilation (
id BIGINT GENERATED BY DEFAULT AS IDENTITY,
pinned boolean,
title VARCHAR(50),
    CONSTRAINT pk_compilation_id PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS compilation_events (
compilation_id BIGINT,
event_id BIGINT,
CONSTRAINT compilation_compilation_events_compilation_id_fk
        FOREIGN KEY (compilation_id) REFERENCES compilation (id) ON DELETE CASCADE,
CONSTRAINT compilation_compilation_events_event_id_fk
        FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE,
CONSTRAINT compilation_events_unique_fk UNIQUE (compilation_id, event_id)
);